---
title: "B356-nfl-elo-rating"
author: "Abe Leininger"
date: "2023-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

# Load data

```{r}
nfl_games <- read.csv("../data/nfl-games2002-2022.csv")
nfl_scores <- read.csv("../data/nfl_scores.csv")
```

# NFL Games dataset from 2002 to 2022

```{r}
nfl_games <- nfl_games %>% mutate(year = as.integer(substring(date, 1, 4)))
```

```{r}
nfl_years <- subset(nfl_games, nfl_games$year %in% c(2019, 2020, 2021, 2022))
nfl_2022 <- subset(nfl_games, nfl_games$year %in% c(2022))
```

```{r}
nfl_scores_year <- subset(nfl_scores, nfl_scores$schedule_season %in% c(2019, 2020, 2021, 2022))
nfl_scores_year
```

```{r}
# Using the Elo rating system calculate the expected probability of winning between two ratings
calc_expected_result <- function(team_rating, opp_rating){
  return(1 / (1 + 10 ** ((opp_rating - team_rating) / 400))) 
}
```


```{r}
# Update the Elo of a team given the result of a performance
update_ratings <- function(team_rating, opp_rating, actual, k=20){
  expected <- calc_expected_result(team_rating, opp_rating)
  new <- team_rating + k * (actual - expected)
  return(new)
}
```

```{r}
# Given game data update the elo ratings of a team based on the results
sim_elo_rankings <- function(games){
  elo_data <- data.frame(
    Team = unique(data$team_home),
    Elo = 1500
  )
  
  for(i in 1:nrow(games)){
    away_team <- games$team_away[i]
    home_team <- games$team_home[i]
    
    score_away <- games$score_away[i]
    score_home <- games$score_home[i]
    
    away_elo <- elo_data[elo_data$Team == away_team,]$Elo
    home_elo <- elo_data[elo_data$Team == home_team,]$Elo
    
    new_away_elo <- update_ratings(away_elo, home_elo, score_away / (score_away + score_home))
    new_home_elo <- update_ratings(home_elo, away_elo, score_home / (score_home + score_away))
    
    elo_data <- elo_data %>% mutate(Elo = ifelse(Team == away_team, new_away_elo, Elo))
    elo_data <- elo_data %>% mutate(Elo = ifelse(Team == home_team, new_home_elo, Elo))
  }
  
  return(elo_data)
}
```

```{r}
sim_elo <- sim_elo_rankings(nfl_scores_year)
sim_elo[order(sim_elo$Elo),]
```

```{r}
nfl_scores_year
```

```{r}
monte_carlo <- function(elo_rankings, from){
  weeks <- c("14", "15", "16", "17", "18")
  
  for(week in weeks){
     
  }
}
```







